stages:
  - test

test:
  image: maven:3.8.5-jdk-11  # Use a Maven image with the desired JDK
  stage: test
  script:
    - mvn clean test  # Runs Maven clean and test
  artifacts:
    reports:
      junit: target/surefire-reports/*.xml  # Collect JUnit test reports
  only:
    - branches  # Run this job for all branches