stages:
  - build
  - test
  - deploy

variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end"

cache:
  paths:
    - .m2/repository/

before_script:
  - apt-get update -y && apt-get install -y maven

build_job:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean compile
  artifacts:
    paths:
      - target/
  only:
    - branches

test_job:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
  dependencies:
    - build_job
  artifacts:
    when: always
    reports:
      junit: target/surefire-reports/*.xml
  only:
    - branches

deploy_job:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  dependencies:
    - test_job
  only:
    - branches
  when: on_success